# -*- coding: utf-8 -*-
"""basic_program.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16V6jD7Dv82sXlUWomUKHf2By1XVPlf9q
"""

# basic_program.py
def greet(name):
    return f"Hello, {name}!"

if __name__ == "__main__":
    name = input("Enter your name: ")
    print(greet(name))